ColourCoded.UI/Areas/Security/Controllers/PermissionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ColourCoded.UI.Areas.Security.Models.Login;
using ColourCoded.UI.Areas.Security.Models.Permissions;
using ColourCoded.UI.Areas.Security.Models.Permissions.RequestModels;
using ColourCoded.UI.Shared;
using ColourCoded.UI.Shared.WebApiCaller;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace ColourCoded.UI.Areas.Security.Controllers
{
  [Area("Security")]
  [Authorize]
  public class PermissionsController : Controller
  {
    protected IWebApiCaller WebApiCaller;
    protected ICookieHelper CookieHelper;
    protected UserModel CurrentUser;

    public PermissionsController(IWebApiCaller webApiCaller, ICookieHelper cookieHelper)
    {
      WebApiCaller = webApiCaller;
      CookieHelper = cookieHelper;
      CurrentUser = CookieHelper.GetCookie<UserModel>("LoggedInUser");
    }

    public ViewResult Index()
    {
      return View();
    }

    public JsonResult GetArtifacts()
    {
      return Json(WebApiCaller.PostAsync<List<ArtifactModel>>("WebApi:Permissions:GetAllArtifacts", null));
    }

    [HttpPost]
    public JsonResult AddArtifact(AddArtifactRequestModel requestModel)
    {
      requestModel.CreateUser = CurrentUser.Username;

      return Json(WebApiCaller.PostAsync<ValidationResult>("WebApi:Permissions:AddArtifact", requestModel));
    }

    [HttpPost]
    public JsonResult EditArtifact(EditArtifactRequestModel requestModel)
    {
      requestModel.CreateUser = CurrentUser.Username;

      return Json(WebApiCaller.PostAsync<ValidationResult>("WebApi:Permissions:EditArtifact", requestModel));
    }

    [HttpPost]
    public JsonResult RemoveArtifact(RemoveArtifactRequestModel requestModel)
    {
      WebApiCaller.PostAsync<string>("WebApi:Permissions:RemoveArtifact", requestModel);

      return Json("Success");
    }

    [HttpPost]
    public JsonResult GetPermissions(FindPermissionsRequestModel requestModel)
    {
      return Json(WebApiCaller.PostAsync<List<PermissionModel>>("WebApi:Permissions:Find", requestModel));
    }

    [HttpPost]
    public JsonResult AddPermission(AddPermissionRequestModel requestModel)
    {
      requestModel.CreateUser = CurrentUser.Username;

      return Json(WebApiCaller.PostAsync<ValidationResult>("WebApi:Permissions:Add", requestModel));
    }

    [HttpPost]
    public JsonResult RemovePermission(RemovePermissionRequestModel requestModel)
    {
      WebApiCaller.PostAsync<string>("WebApi:Permissions:Remove", requestModel);

      return Json("Success");
    }

  }
}

ColourCoded.UI/Areas/Security/Controllers/RolesController.cs
using Microsoft.AspNetCore.Mvc;
using ColourCoded.UI.Shared;
using ColourCoded.UI.Shared.WebApiCaller;
using ColourCoded.UI.Areas.Security.Models.Role;
using ColourCoded.UI.Areas.Security.Models.Role.RequestModels;
using System.Collections.Generic;
using Microsoft.AspNetCore.Authorization;
using ColourCoded.UI.Areas.Security.Models.Login;

namespace ColourCoded.UI.Areas.Security.Controllers
{
  [Area("Security")]
  [Authorize]
  public class RolesController : Controller
  {
    protected IWebApiCaller WebApiCaller;
    protected ICookieHelper CookieHelper;
    protected UserModel CurrentUser;

    public RolesController(IWebApiCaller webApiCaller, ICookieHelper cookieHelper)
    {
      WebApiCaller = webApiCaller;
      CookieHelper = cookieHelper;
      CurrentUser = CookieHelper.GetCookie<UserModel>("LoggedInUser");
    }

    public ViewResult Index()
    {
      return View();
    }

    public JsonResult GetAll()
    {
      return Json(WebApiCaller.PostAsync<List<RoleModel>>("WebApi:Role:GetAll", null));
    }

    public JsonResult FilterUsernames(string term)
    {
      return Json(WebApiCaller.PostAsync<List<string>>("WebApi:Role:SearchUsers", new SearchUsersRequestModel { SearchTerm = term }));
    }

    [HttpPost]
    public JsonResult AddRole(AddRoleRequestModel requestModel)
    {
      requestModel.CreateUser = CurrentUser.Username;

      return Json(WebApiCaller.PostAsync<ValidationResult>("WebApi:Role:AddRole", requestModel));
    }

    [HttpPost]
    public JsonResult EditRole(EditRoleRequestModel requestModel)
    {
      requestModel.CreateUser = CurrentUser.Username;

      return Json(WebApiCaller.PostAsync<ValidationResult>("WebApi:Role:EditRole", requestModel));
    }

    [HttpPost]
    public JsonResult RemoveRole(RemoveRoleRequestModel requestModel)
    {
      WebApiCaller.PostAsync<string>("WebApi:Role:RemoveRole", requestModel);

      return Json("Success");
    }

    [HttpPost]
    public JsonResult GetRoleMembers(FindRoleMembersRequestModel requestModel)
    {
      return Json(WebApiCaller.PostAsync<List<RoleMemberModel>>("WebApi:Role:GetRoleMembers", requestModel));
    }

    [HttpPost]
    public JsonResult AddRoleMember(AddRoleMemberRequestModel requestModel)
    {
      requestModel.CreateUser = CurrentUser.Username;

      return Json(WebApiCaller.PostAsync<ValidationResult>("WebApi:Role:AddRoleMember", requestModel));
    }

    [HttpPost]
    public JsonResult RemoveRoleMember(RemoveRoleMemberRequestModel requestModel)
    {
      WebApiCaller.PostAsync<string>("WebApi:Role:RemoveRoleMember", requestModel);

      return Json("Success");
    }
  }
}

ColourCoded.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link href="~/lib/font-awesome/css/font-awesome.css" rel="stylesheet" />
  <link href="~/lib/bootstrap/css/bootstrap.css" rel="stylesheet" />
  <link href="~/css/sb-admin-2.css" rel="stylesheet" />
  <link href="~/css/metisMenu.css" rel="stylesheet" />
  <link href="~/lib/jquery-ui/jquery-ui.css" rel="stylesheet" />

  <script src="~/lib/jquery/dist/jquery.min.js"></script>
  <script src="~/lib/jquery-ui/jquery-ui-1.12.1.min.js"></script>
  <script src="~/lib/metismenu/metisMenu.min.js"></script>
  <script src="~/lib/theme/sb-admin-2.js"></script>
  <script src="~/lib/bootstrap/js/bootstrap.js"></script>
  <script src="~/lib/jquery-ui/jquery-ui-1.12.1.js"></script>
</head>
<body>
  <div id="wrapper">
    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" id="burger">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand">CC Invoice</a>
        <ul class="nav navbar-top-links navbar-right" style="">
          <!-- /. Top right corner dropdown -->
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
              <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
            </a>
            <ul class="dropdown-menu dropdown-user">
              <li>
                <a asp-area="Security" asp-controller="Authenticate" asp-action="ChangePasswordIndex"><i class="fa fa-user fa-fw"></i> Update Profile</a>
              </li>
              <li class="divider"></li>
              <li>
                <a data-toggle="modal" data-target="#SignOutModal" style="cursor:pointer"><i class="fa fa-sign-out fa-fw"></i> Sign Out</a>
              </li>
            </ul>
            <!-- /.dropdown-user -->
          </li>
          <!-- /. Top right corner dropdown -->
        </ul>
        <!-- /.navbar-top-links -->
      </div>
      <!-- /.navbar-header -->

      <div class="navbar-default sidebar" role="navigation">
        <div class="sidebar-nav navbar-collapse">
          <ul class="nav" id="side-menu">
            @*<li>
              <a><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
            </li>*@
            <li>
              <a asp-area="Orders" asp-controller="Orders" asp-action="Index"><i class="fa fa-home  fa-fw"></i> Home</a>
            </li>
            <li>
              <a><i class="fa fa-users fa-fw"></i> Manage Customers</a>
              @*<ul class="nav nav-second-level">
                <li>
                  <a>Manage Customers</a>
                </li>
                <li>
                  <a>Statements</a>
                </li>
              </ul>*@
            </li>
            <li>
              <a><i class="fa fa-product-hunt fa-fw"></i> Manage Products</a>
            </li>
            <li>
              <a><i class="fa fa-building fa-fw"></i> Company Profile</a>
            </li>
            <li>
              <a><i class="fa fa-lock fa-fw"></i> Security<span class="fa arrow"></span></a>
              <ul class="nav nav-second-level">
                <li>
                  <a asp-area="Security" asp-controller="Roles" asp-action="Index">Roles</a>
                </li>
                <li>
                  <a asp-area="Security" asp-controller="Permissions" asp-action="Index">Permissions</a>
                </li>
              </ul>
            </li>
          </ul>
        </div>
        <!-- /.sidebar-collapse -->
      </div>
      <!-- /.navbar-static-side -->
    </nav>

    <div id="page-wrapper">
      @RenderBody()
    </div>

    <!-- Loader Modal -->
    <div class="modal fade" id="loader" tabindex="-1" role="dialog" aria-labelledby="loadMeLabel">
      <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
          <div class="loader"></div>
        </div>
      </div>
    </div>

    <!-- Sign Out Modal -->
    <div class="modal fade" id="SignOutModal" tabindex="-1" role="dialog" aria-labelledby="SignOutModalLabel" aria-hidden="true">
      <div class="modal-dialog" style="width:250px">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title" id="SignOutModalLabel">Sign Out</h4>
          </div>
          <div class="modal-body">
            Are you sure you would like to sign out?
          </div>
          <div class="modal-footer">
            <button type="button" class="btn-thin btn-primary" id="logout">Yes</button>
            <button type="button" class="btn-thin btn-default" data-dismiss="modal">Close</button>
          </div>
        </div>
        <!-- /.modal-content -->
      </div>
      <!-- /.modal-dialog -->
    </div>
    <!-- /.modal -->

  </div>

  @RenderSection("Scripts", required: false)

  <script>
    $('#logout').click(function (event) {
      window.location.href = '@Url.Action("Logout", "Authenticate", new { @area="Security"})';
    });


    function GlobalLoader(visible) {

      if (visible) {
        $("#loader").modal({
          backdrop: "static", //remove ability to close modal with click
          keyboard: false, //remove option to close with keyboard
          show: true //Display loader!
        });
      }
      else {
        $("#loader").modal("hide");
      }

    }
  </script>

</body>
</html>